name: Auto Tag Version

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from package.json
        id: package_version
        run: echo "VERSION=v$(jq -r .version electron-app/package.json)" >> $GITHUB_ENV

      - name: Create GitHub Tag
        run: |
          git config user.name "lan-installer-bot"
          git config user.email "bot@lan.local"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/containerguy/lan_installer.git
          git tag $VERSION
          git push origin $VERSION
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
