name: Build & Release LAN Installer

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd electron-app
          npm install

      - name: Prepare changelog generation
        run: |
          copy electron-app\package.json .
          npx auto-changelog -p

      - name: Build portable executable
        run: |
          cd electron-app
          npx electron-builder --win portable

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            electron-app/dist/*.exe
            electron-app/dist/*.yml
            electron-app/dist/*.nupkg
            CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
