name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # jeden Montag um 2:00 Uhr UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.GH_TOKEN }}
